# Production profile (Microsoft SQL Server)
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=SBA301;encrypt=true;trustServerCertificate=true}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:12345}

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

CLOUDINARY_URL=cloudinary://<756322159498959>:<hcVcmekTF-dyx2f2H37F7IwW_vE>@dshnllngm
cloudinary.cloud-name=dshnllngm
cloudinary.api-key=756322159498959
cloudinary.api-secret=hcVcmekTF-dyx2f2H37F7IwW_vE