server {
    listen 80;
    server_name localhost;

    # Phục vụ giao diện Frontend tĩnh
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Chuyển hướng các request API sang container Backend (Tránh lỗi CORS)
    location /api/ {
        proxy_pass http://sba-backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
